config/routes.rb
Rails.application.routes.draw do
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"

  root 'home#index'
  resources :sessions
  resources :users
  resources :password_resets
  resources :images

  resources :callbacks do
    collection do
      post 'image_upload_callback'
    end
  end

  #注册 
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  
  get 'sessions/auth_callback' => 'sessions#auth_callback'
  #登入登出 
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'account_activation/:id',to: 'users#account_activation',as: :user_account_activation
  post 'users/send_verify_code' => 'users#send_verify_code'


  resources :articles

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/shared/_errors_messages.html.erb
<%if user.errors.any?%>
  <div id="error_explanation">
    <div class="alert alert-danger">
      表单中有<%= user.errors.count%>个错误
    </div>
    <ul>

      <%user.errors.full_messages.each do |msg|%>

        <li><%=msg%></li>
      <%end%>
    </ul>
  </div>
<%end%>

app/views/shared/_header_v1.html.erb
<div class="row headerv1">
  <div class="container">

    <div class="col-md-3 col-sm-3 col-xs-3" >
      <%= image_tag("http://yamaha.com.cn/assets/logo_yamaha-f2cf48eec4b4595c30ca169ce5eb938a.gif",class: "logo")%>
    </div>

    <div class="col-md-6 col-sm-6 col-xs-6">
      <div class="top-search">
          <form action="/search" method="get">
            <div class="input-group">
              <input type="text" name="q" class="form-control" />
              <span class="input-group-btn">
                <button class=" btn btn-default" type="submit">
                  搜索
                </button>
              </span>
            </div>
          </form>
        </div>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-3 ">
      

      <div class="dropdown  pull-right" style="padding-left:10px;margin:0;">
        <span class="dropdown-toggle nav-menu" data-toggle="dropdown">
          <i class="fa-left fa fa-3x fa-plus-square" aria-hidden="true"></i>
        </span>
        <ul class="dropdown-menu dropdown-menu-right">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li> <%=link_to "发布原创",new_article_path if current_user%> </li>
          <li role="separator" class="divider"></li>
          <li><%=link_to("退出",logout_path,method: :delete) if current_user%></li>
        </ul>
      </div>
      <div class="pull-right">
        <%if current_user%>
          <span style="line-height:40px;vertical-align:middle;"><%= link_to current_user.name, current_user%></span>
        <%else%>
          <span style="line-height:40px;vertical-align:middle;">
            <%= link_to "登陆",login_path%>
            <%= link_to "注册",signup_path%>
          </span>
        <%end%>
        <a href="" style="line-height:40px;vertical-align:middle;" data-toggle="modal" data-target="#modal-login"></a>
      </div>

    </div>
  </div>

  <ul class="home-nav">
    <li class="active"><a href="">产品</a></li>
    <li><a href="">音乐</a></li>
    <li><a href="">销售网络</a></li>
    <li><a href="">客户支持</a></li>
    <li><a href="">新闻互动</a></li>
    <li><a href="">关于雅马哈</a></li>
  </ul>
</div>

<script type="text/javascript">
  $(function(){
    $(".dropdown").mouseover(function() {   
     $(this).addClass('open'); }).mouseout(function() {$(this).removeClass('open'); }); 
    });
</script>

app/views/shared/_titled_table.html.erb
<table class="title">
  <%collection.in_groups_of(columns) do |rows|%>
    <tr>
      <% row.each do |item|%>
        <td id="<%= dom_id()%>">
          <div class="left">
            <%= link_to thumbnail.call(item),link.call(item)%>
          </div>
          <div class="left">
            <div class="title"><%= link_to title.call(item), link.call(item)%></div>
            <div class="description"><%= link_to description.call(item)%></div>
          </div>
        </td>
      <%end%>
    </tr>
  <%end%>  
</table>

<!-- 调用时 -->
<!-- <%#= titled(cities,link: ->(city){city_ptah(city)})%> -->
<!-- 当对象不同时 -->
 <!-- <%#= titled(users,link: ->(user){user_path(user)},thumbnail: ->(user){user.avatar},title: ->(user){user.name},columns: 5)%> -->