config/routes.rb
Rails.application.routes.draw do
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"

  root 'home#index'
  resources :sessions
  resources :users
  resources :password_resets
  resources :images

  resources :callbacks do
    collection do
      post 'image_upload_callback'
    end
  end

  #注册 
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  
  get 'sessions/auth_callback' => 'sessions#auth_callback'
  #登入登出 
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'account_activation/:id',to: 'users#account_activation',as: :user_account_activation
  post 'users/send_verify_code' => 'users#send_verify_code'


  resources :articles

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/shared/login/_login_or_registration_form.html.erb
<div class="login_or_register ">
  <div class="login-triggle">
    <%= link_to "登陆",login_path,class: "#{controller_name=='sessions' ? 'active' : ''}"%>
    &bull;
    <%= link_to "注册", signup_path,class: "#{controller_name=='sessions' ? '' : 'active'}"%>
  </div>
  <div class="login">
    <%= form_for(@user, url: (controller_name == "users" ? signup_path : login_path), method: :post) do |f| %>


      <% if controller_name == "users"%>
        <div class="form-group">
          <%= f.text_field :name, autofocus: true,class: "form-control input-lg", placeholder: "请输入昵称" %>
        </div>
        <div class="error"><%= @user.errors[:name].join(",")%></div>
      <%end%>

      <div class="form-group">
        <%= f.text_field :account, autofocus: true,class: "form-control  account input-lg",id: "account",autocomplete: "off", placeholder: "请输入邮箱或者手机号" %>
      </div>
      <div class="error"><%= (@user.errors[:account]+@user.errors[:email]+@user.errors[:mobile]).join(",")%></div>

      <div class="form-group">

        <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <%= f.password_field :password, autocomplete: "off",class: "form-control input-lg",placeholder: "请输入密码" %>
        <div class="error"><%=@user.errors[:password].join(",")%></div>
        <%= link_to "忘记密码",new_password_reset_path if controller_name == "sessions" %>
      </div>
      <div class="form-group">
        <%= f.password_field :password_confirmation, autocomplete: "off",class: "form-control input-lg",placeholder: "请再次输入密码" if controller_name == "users" %>
      </div>

      <div class="form-group">
        <div class="input-group">
          <%= rucaptcha_input_tag(class: 'form-control input-lg', placeholder: "请输入验证码") %>
          <span class="input-group-addon input-group-captcha">
            <a class="rucaptcha-image-box" href="#">
              <%= rucaptcha_image_tag %>
            </a>
          </span>
        </div>
        <div class="error"><%=@user.errors[:base].join(",")%></div>
      </div>
      <%if controller_name == "users"%>

        <div class="form-group sms  hidden">
          <%= f.text_field :verify_code, class: "form-control input-lg",placeholder: "短信验证码"%>
          <%= link_to "点击获取", "javascript:void(0);", class: "send-sms js-send-sms",data: {env: "reg"}%>
          <div class="error"><%=@user.errors[:verify_code].join(",")%></div>
        </div>
      <%end%>

      <div class="submit">
        <%= f.submit "#{controller_name == 'users' ? '注册' : '登陆'}",class: "btn btn-success btn-block" %>
      </div>


      <div>
        <h4>第三方帐号登录</h4>
        <a href="/auth/wechat"><i class="fa fa-2x fa-weixin"></i></a>
      </div>

    <% end %>
  </div>
      
</div>